<a href="https://colab.research.google.com/github/ram-polisetti/MachineLearning/blob/main/Pytorch_d2l_ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch

In [7]:
x = torch.arange(12, dtype=torch.float32)

In [9]:
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

Number of elements

In [11]:
x.numel()

12

In [12]:
x.shape

torch.Size([12])

In [13]:
x = x.reshape(3, 4)

In [14]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
x.reshape(4, -1)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [17]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
torch.ones((4, 6, 9))

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       

In [22]:
torch.randn(3, 4)

tensor([[-0.3929, -0.0441, -0.1664,  2.1361],
        [ 1.1173, -1.6347, -0.2483, -0.2965],
        [ 0.4448, -0.5802,  0.3414, -0.2578]])

In [31]:
import numpy as np
x = np.arange(21)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [32]:
x.dtype

dtype('int64')

In [33]:
x = torch.tensor(x)

In [34]:
x.dtype

torch.int64

In [47]:
x.reshape(3, 7)

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13],
        [14, 15, 16, 17, 18, 19, 20]])

In [48]:
x[-1]

tensor(20)

In [49]:
x[1:3]

tensor([1, 2])

In [50]:
x[1, 2] = 17

IndexError: too many indices for tensor of dimension 1

In [51]:
 torch.randn(3, 4)

tensor([[-0.3886,  1.2630, -0.5583, -0.9963],
        [ 1.0968,  0.2364, -0.9331,  0.6329],
        [ 0.5061, -1.0026,  0.2664, -2.0634]])

In [53]:
x = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

In [54]:
x[-1]

tensor([4, 3, 2, 1])

In [55]:
x[1:3]

tensor([[1, 2, 3, 4],
        [4, 3, 2, 1]])

In [56]:
x[1, 2]

tensor(3)

In [57]:
x[1, 2] = 17

In [58]:
x

tensor([[ 2,  1,  4,  3],
        [ 1,  2, 17,  4],
        [ 4,  3,  2,  1]])

In [59]:
x[:2, :]

tensor([[ 2,  1,  4,  3],
        [ 1,  2, 17,  4]])

In [60]:
x[:2, :] = 15
x

tensor([[15, 15, 15, 15],
        [15, 15, 15, 15],
        [ 4,  3,  2,  1]])

In [61]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

In [62]:
x + y

tensor([ 3.,  4.,  6., 10.])

In [63]:
x - y

tensor([-1.,  0.,  2.,  6.])

In [64]:
x*y

tensor([ 2.,  4.,  8., 16.])

In [65]:
x/y

tensor([0.5000, 1.0000, 2.0000, 4.0000])

In [66]:
x//y

tensor([0., 1., 2., 4.])

In [67]:
x**y

tensor([ 1.,  4., 16., 64.])

In [68]:
x ==y

tensor([False,  True, False, False])

In [69]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [70]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [71]:
X.sum()

tensor(66.)

In [72]:
y.sum()

tensor(8)

## Broadcasting

In [73]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [75]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [76]:
z = torch.zeros_like(Y)
print('id(z)', id(z))
z[:] = X + Y

print('id(z)', id(z))


id(z) 136793204293072
id(z) 136793204293072


In [78]:
before = id(X)
X += Y
id(X) == before

True

In [79]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [80]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

In [81]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('''NumRooms,RoofType,Price
NA,NA,127500
2,NA,106000
4,Slate,178100
NA,NA,140000''')

In [93]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms RoofType   Price
0       NaN      NaN  127500
1       2.0      NaN  106000
2       4.0    Slate  178100
3       NaN      NaN  140000


In [94]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:,2]
inputs, targets

(   NumRooms RoofType
 0       NaN      NaN
 1       2.0      NaN
 2       4.0    Slate
 3       NaN      NaN,
 0    127500
 1    106000
 2    178100
 3    140000
 Name: Price, dtype: int64)

In [89]:
inputs, targets = data.loc[:, ['NumRooms', 'RoofType']], data.loc[:,['Price']]

In [90]:
inputs, targets = data[['NumRooms', 'RoofType']], data[['Price']]

In [91]:
inputs, targets

(   NumRooms RoofType
 0       NaN      NaN
 1       2.0      NaN
 2       4.0    Slate
 3       NaN      NaN,
     Price
 0  127500
 1  106000
 2  178100
 3  140000)

In [95]:
inputs, targets = data.iloc[:, 0:2], data.iloc[:, 2]

In [96]:
inputs, targets

(   NumRooms RoofType
 0       NaN      NaN
 1       2.0      NaN
 2       4.0    Slate
 3       NaN      NaN,
 0    127500
 1    106000
 2    178100
 3    140000
 Name: Price, dtype: int64)

In [97]:
inputs = pd.get_dummies(inputs, dummy_na=True)
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       NaN           False          True
1       2.0           False          True
2       4.0            True         False
3       NaN           False          True


In [98]:
inputs = inputs.fillna(inputs.mean())
print(inputs)

   NumRooms  RoofType_Slate  RoofType_nan
0       3.0           False          True
1       2.0           False          True
2       4.0            True         False
3       3.0           False          True


In [99]:
X = torch.tensor(inputs.to_numpy(dtype=float))
y = torch.tensor(targets.to_numpy(dtype=float))
X, y

(tensor([[3., 0., 1.],
         [2., 0., 1.],
         [4., 1., 0.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500., 106000., 178100., 140000.], dtype=torch.float64))