In [49]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR

In [50]:
bitcoin_data = pd.read_csv('bitcoin.csv')
bitcoin_data.head()

Date        Price
0  5/23/2019  7881.846680
1  5/24/2019  7987.371582
2  5/25/2019  8052.543945
3  5/26/2019  8673.215820
4  5/27/2019  8805.778320

In [51]:
bitcoin_data.shape

(367, 2)

In [52]:
bitcoin_data.Date.tail()

362    5/19/2020
363    5/20/2020
364    5/21/2020
365    5/22/2020
366    5/23/2020
Name: Date, dtype: object

In [53]:
bitcoin_data.iloc[30:49]

Date        Price
30  6/22/2019  10701.69141
31  6/23/2019  10855.37109
32  6/24/2019  11011.10254
33  6/25/2019  11790.91699
34  6/26/2019  13016.23145
35  6/27/2019  11182.80664
36  6/28/2019  12407.33203
37  6/29/2019  11959.37109
38  6/30/2019  10817.15527
39   7/1/2019  10583.13477
40   7/2/2019  10801.67773
41   7/3/2019  11961.26953
42   7/4/2019  11215.43750
43   7/5/2019  10978.45996
44   7/6/2019  11208.55078
45   7/7/2019  11450.84668
46   7/8/2019  12285.95801
47   7/9/2019  12573.81250
48  7/10/2019  12156.51270

In [54]:
bitcoin_data.drop(['Date'], axis=1, inplace=True)

## Create another column shifted 30 units up

In [55]:
prediction_days = 30
bitcoin_data['Prediction'] = bitcoin_data.Price.shift(-prediction_days)

In [56]:
bitcoin_data.head()

Price   Prediction
0  7881.846680  10701.69141
1  7987.371582  10855.37109
2  8052.543945  11011.10254
3  8673.215820  11790.91699
4  8805.778320  13016.23145

In [57]:
bitcoin_data.tail()

Price  Prediction
362  9729.038086         NaN
363  9522.981445         NaN
364  9081.761719         NaN
365  9182.577148         NaN
366  9180.045898         NaN

Create the independent data set.


Here we will convert the data frame into a numpy array and drop the prediction column


In [58]:
X = np.array(bitcoin_data.drop(['Prediction'], axis=1))
X

array([[ 7881.84668 ],
       [ 7987.371582],
       [ 8052.543945],
       [ 8673.21582 ],
       [ 8805.77832 ],
       [ 8719.961914],
       [ 8659.487305],
       [ 8319.472656],
       [ 8574.501953],
       [ 8564.016602],
       [ 8742.958008],
       [ 8208.995117],
       [ 7707.770996],
       [ 7824.231445],
       [ 7822.023438],
       [ 8043.951172],
       [ 7954.12793 ],
       [ 7688.077148],
       [ 8000.32959 ],
       [ 7927.714355],
       [ 8145.857422],
       [ 8230.923828],
       [ 8693.833008],
       [ 8838.375   ],
       [ 8994.488281],
       [ 9320.352539],
       [ 9081.762695],
       [ 9273.521484],
       [ 9527.160156],
       [10144.55664 ],
       [10701.69141 ],
       [10855.37109 ],
       [11011.10254 ],
       [11790.91699 ],
       [13016.23145 ],
       [11182.80664 ],
       [12407.33203 ],
       [11959.37109 ],
       [10817.15527 ],
       [10583.13477 ],
       [10801.67773 ],
       [11961.26953 ],
       [11215.4375  ],
       [109

In [59]:
X = X[:len(bitcoin_data)-prediction_days]
X

array([[ 7881.84668 ],
       [ 7987.371582],
       [ 8052.543945],
       [ 8673.21582 ],
       [ 8805.77832 ],
       [ 8719.961914],
       [ 8659.487305],
       [ 8319.472656],
       [ 8574.501953],
       [ 8564.016602],
       [ 8742.958008],
       [ 8208.995117],
       [ 7707.770996],
       [ 7824.231445],
       [ 7822.023438],
       [ 8043.951172],
       [ 7954.12793 ],
       [ 7688.077148],
       [ 8000.32959 ],
       [ 7927.714355],
       [ 8145.857422],
       [ 8230.923828],
       [ 8693.833008],
       [ 8838.375   ],
       [ 8994.488281],
       [ 9320.352539],
       [ 9081.762695],
       [ 9273.521484],
       [ 9527.160156],
       [10144.55664 ],
       [10701.69141 ],
       [10855.37109 ],
       [11011.10254 ],
       [11790.91699 ],
       [13016.23145 ],
       [11182.80664 ],
       [12407.33203 ],
       [11959.37109 ],
       [10817.15527 ],
       [10583.13477 ],
       [10801.67773 ],
       [11961.26953 ],
       [11215.4375  ],
       [109

Create the dependent data set
 
 convert the data frame into a numpy array

In [60]:
y = np.array(bitcoin_data.Prediction)
y = y[:-prediction_days]
y

array([10701.69141 , 10855.37109 , 11011.10254 , 11790.91699 ,
       13016.23145 , 11182.80664 , 12407.33203 , 11959.37109 ,
       10817.15527 , 10583.13477 , 10801.67773 , 11961.26953 ,
       11215.4375  , 10978.45996 , 11208.55078 , 11450.84668 ,
       12285.95801 , 12573.8125  , 12156.5127  , 11358.66211 ,
       11815.98633 , 11392.37891 , 10256.05859 , 10895.08984 ,
        9477.641602,  9693.802734, 10666.48242 , 10530.73242 ,
       10767.13965 , 10599.10547 , 10343.10645 ,  9900.767578,
        9811.925781,  9911.841797,  9870.303711,  9477.677734,
        9552.860352,  9519.145508,  9607.423828, 10085.62793 ,
       10399.66895 , 10518.17481 , 10821.72656 , 10970.18457 ,
       11805.65332 , 11478.16895 , 11941.96875 , 11966.40723 ,
       11862.93652 , 11354.02441 , 11523.5791  , 11382.61621 ,
       10895.83008 , 10051.7041  , 10311.5459  , 10374.33887 ,
       10231.74414 , 10345.81055 , 10916.05371 , 10763.23242 ,
       10138.04981 , 10131.05566 , 10407.96484 , 10159.

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [62]:
predictionDays_array = np.array(bitcoin_data.drop(['Prediction'], axis=1))[-prediction_days:]
predictionDays_array

array([[7550.900879],
       [7569.936035],
       [7679.867188],
       [7795.601074],
       [7807.058594],
       [8801.038086],
       [8658.553711],
       [8864.766602],
       [8988.59668 ],
       [8897.46875 ],
       [8912.654297],
       [9003.070313],
       [9268.761719],
       [9951.518555],
       [9842.666016],
       [9593.896484],
       [8756.430664],
       [8601.795898],
       [8804.477539],
       [9269.987305],
       [9733.72168 ],
       [9328.197266],
       [9377.013672],
       [9670.739258],
       [9726.575195],
       [9729.038086],
       [9522.981445],
       [9081.761719],
       [9182.577148],
       [9180.045898]])

In [63]:
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.00001)
svr_rbf.fit(X_train, y_train)

SVR(C=1000.0, gamma=1e-05)

In [64]:
svr_rbf_confidence = svr_rbf.score(X_test, y_test)
print('svr_rbf accuracy: {}'.format(svr_rbf_confidence))

svr_rbf accuracy: 0.31093819195963657


In [65]:
svm_prediction = svr_rbf.predict(X_test)
svm_prediction

array([ 8337.91445922,  8453.91625467,  8645.30813412, 10153.73001125,
        8346.84389633,  8326.72024293,  9203.7331325 ,  8225.09580804,
        8828.28319324,  8737.6245658 ,  9221.71609919,  9179.11444101,
        8037.32464081,  7754.07345514,  8727.45877908,  7801.43650133,
        8659.19592482,  8031.14710273, 10296.57034325,  8014.52462457,
        9408.94586341,  8898.35083191,  8328.57820291,  9978.74789756,
        8984.41816556,  8598.86132426,  8817.96239361,  9532.43483674,
        8497.13391665,  9210.85368801,  7645.4387829 ,  7437.47649583,
        8408.51460545,  8707.16660945,  8793.1118086 ,  9194.00761077,
       10158.30769028,  7673.65252599,  8360.81307062, 10256.13351205,
        8769.08921855,  8813.43002418,  8069.33337509,  8910.81806806,
       10267.53290189,  9668.61655292,  9186.97947343,  8635.49591743,
        8092.88136557, 10297.20403862,  9214.07958228,  8819.71174496,
        9448.09233146,  9220.88459446,  8455.59010354,  8877.77356476,
      

In [66]:
y_test

array([ 5392.314941,  8321.756836,  8660.700195, 10334.97461 ,
        8103.911133,  7988.560547,  9551.714844,  8562.454102,
        9650.174805,  9350.529297,  9360.879883,  7400.899414,
        9180.962891,  7290.088379,  9663.181641,  6880.323242,
        8078.203125,  8293.868164, 10399.66895 ,  8343.276367,
       10855.37109 ,  8807.010742,  8245.915039, 10821.72656 ,
       11959.37109 ,  8336.555664,  9182.577148,  8151.500488,
       10159.96094 , 10801.67773 ,  6881.958496,  6642.109863,
        7200.174316,  7238.966797,  8827.764648,  7564.345215,
       11354.02441 ,  7189.424805,  9842.666016, 11523.5791  ,
        9951.518555,  8144.194336,  9122.545898,  9522.981445,
        9552.860352, 10763.23242 ,  9889.424805,  9690.142578,
        7355.628418, 10346.76074 ,  6793.624512,  7271.78125 ,
        9427.6875  ,  9256.148438,  8486.993164,  9392.875   ,
        5225.629395,  7531.663574, 12573.8125  ,  6734.803711,
        7448.307617,  7679.867188,  9261.104492, 10347.

In [69]:
# Print the model predictions for the next 30 days
svm_prediction = svr_rbf.predict(predictionDays_array)
print(svm_prediction)
print()
#Print the actual price for bitcoin for last 30 days
print(bitcoin_data.tail(prediction_days))

[7763.53231263 7790.43550272 8234.68653166 8885.30144351 8940.13812203
 9199.57940698 9032.49744022 9029.31440394 8360.23556951 8883.63745885
 8805.37717135 8274.16237706 7933.85047433 8602.0681341  8261.01529559
 8118.25975033 9219.95831447 8858.12239936 9194.62134534 7938.11432433
 7976.40158024 8149.90914698 8300.56833358 7969.85381982 7968.82852745
 7971.24378117 8301.85687486 7881.90050577 7731.11460852 7729.19492274]

           Price  Prediction
337  7550.900879         NaN
338  7569.936035         NaN
339  7679.867188         NaN
340  7795.601074         NaN
341  7807.058594         NaN
342  8801.038086         NaN
343  8658.553711         NaN
344  8864.766602         NaN
345  8988.596680         NaN
346  8897.468750         NaN
347  8912.654297         NaN
348  9003.070313         NaN
349  9268.761719         NaN
350  9951.518555         NaN
351  9842.666016         NaN
352  9593.896484         NaN
353  8756.430664         NaN
354  8601.795898         NaN
355  8804.477539     